import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import Instagram from '../components/Instagram'
import Slider from '../components/Slider'
import { SliderData } from '../components/SliderData'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Fatih Calis Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-32x32.png" />  
      </Head>
      <Hero heading='Fatih Calis' message='Fullstack Developer.'/>
      <Slider slides={SliderData} />
      <Instagram/>
    </div>
  )
}
