import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import Instagram from '../components/Instagram'
import Slider from '../components/Slider'
import { SliderData } from '../components/SliderData'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Fatih Calis Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-32x32.png" />  
      </Head>
      <Hero heading='Fatih Calis' message='Interested in IT and an expert front-end developer, interested in writing codes, skilled at developing complex solutions, creating user friendly designs, excellent and dependable team player with strong analytical thinking skills. Quick to learn and adapt to new technologies, and create new solutions according to problems.'/>
      <Slider slides={SliderData} />
      <Instagram/>
    </div>
  )
}
